-- Ejecutar en PDB ORCLPDB1
ALTER SESSION SET CONTAINER=ORCLPDB1;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER edu_R IDENTIFIED BY EduardoRojas123';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER maria_M IDENTIFIED BY MariaMarin123';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER mariana_C IDENTIFIED BY MarianaC123';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER cris_C IDENTIFIED BY CrisC123';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Crear rol de desarrollo
BEGIN
  EXECUTE IMMEDIATE 'CREATE ROLE dev_full';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE,
      CREATE TRIGGER, DROP ANY TABLE, ALTER ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE,
      DELETE ANY TABLE, SELECT ANY TABLE TO edu_R;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE,
      CREATE TRIGGER, DROP ANY TABLE, ALTER ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE,
      DELETE ANY TABLE, SELECT ANY TABLE TO maria_M;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE,
      CREATE TRIGGER, DROP ANY TABLE, ALTER ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE,
      DELETE ANY TABLE, SELECT ANY TABLE TO mariana_C;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE,
      CREATE TRIGGER, DROP ANY TABLE, ALTER ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE,
      DELETE ANY TABLE, SELECT ANY TABLE TO cris_C;

GRANT dev_full TO edu_R, maria_M, mariana_C, cris_C;

ALTER USER maria_M QUOTA UNLIMITED ON USERS;
ALTER USER edu_R QUOTA UNLIMITED ON USERS;
ALTER USER mariana_C QUOTA UNLIMITED ON USERS;
ALTER USER cris_C QUOTA UNLIMITED ON USERS;

COMMIT;